# Yelp dataset configuration
name: yelp
train_data_file: data/yelp/train.csv
dev_data_file: data/yelp/dev.csv
test_data_file: data/yelp/test.csv
embedding_model: stsb-roberta-base-v2
embeddings_file: result/embeddings/stsb-roberta-base-v2/yelp_train_all.embeddings.npz
variation_type: yelp_rephrase_tone
subcategory_source: data/yelp/subcategories
